using System.Text;

namespace AGIQ.CNF;

public sealed class CnfModel
{
    private readonly List<Variable> _variables = new();
    private readonly Dictionary<string, Variable> _byName = new(StringComparer.Ordinal);
    private readonly List<Literal[]> _clauses = new();

    public IReadOnlyList<Variable> Variables => _variables;
    public IReadOnlyList<Literal[]> Clauses => _clauses;

    public int VariableCount => _variables.Count;
    public int ClauseCount => _clauses.Count;

    public Variable Var(string? name = null)
    {
        name = string.IsNullOrWhiteSpace(name) ? $"x{_variables.Count + 1}" : name.Trim();

        if (_byName.TryGetValue(name, out var existing))
            return existing;

        var variable = new Variable(_variables.Count + 1, name);
        _variables.Add(variable);
        _byName.Add(name, variable);
        return variable;
    }

    public Variable[] Vars(string prefix, int count)
    {
        if (count < 1)
            throw new ArgumentOutOfRangeException(nameof(count), "Count must be >= 1.");

        var arr = new Variable[count];
        for (int i = 0; i < count; i++)
            arr[i] = Var($"{prefix}{i + 1}");

        return arr;
    }

    public void AddClause(params Literal[] literals)
    {
        if (literals is null || literals.Length == 0)
            throw new ArgumentException("Clause must contain at least one literal.", nameof(literals));

        foreach (var lit in literals)
        {
            if (lit.VarId < 1 || lit.VarId > _variables.Count)
                throw new InvalidOperationException($"Literal refers to unknown variable id {lit.VarId}.");
        }

        _clauses.Add(literals.ToArray());
    }

    public void AddOr(params Literal[] literals) => AddClause(literals);

    public void AddUnit(Literal literal) => AddClause(literal);

    public void AddImplication(Literal premise, Literal consequence)
    {
        // premise -> consequence  ===  (!premise OR consequence)
        AddClause(!premise, consequence);
    }

    public void AddEquivalence(Literal a, Literal b)
    {
        // a <-> b  ===  (!a OR b) AND (!b OR a)
        AddImplication(a, b);
        AddImplication(b, a);
    }

    public void AddAtLeastOne(IEnumerable<Literal> literals)
    {
        var arr = literals?.ToArray() ?? throw new ArgumentNullException(nameof(literals));
        if (arr.Length == 0)
            throw new ArgumentException("AtLeastOne requires at least one literal.", nameof(literals));

        AddClause(arr);
    }

    public void AddAtMostOne(IEnumerable<Literal> literals)
    {
        var arr = literals?.ToArray() ?? throw new ArgumentNullException(nameof(literals));
        if (arr.Length <= 1)
            return;

        // Pairwise encoding:
        // For every pair (a,b): (!a OR !b)
        for (int i = 0; i < arr.Length; i++)
        {
            for (int j = i + 1; j < arr.Length; j++)
            {
                AddClause(!arr[i], !arr[j]);
            }
        }
    }

    public void AddExactlyOne(IEnumerable<Literal> literals)
    {
        var arr = literals?.ToArray() ?? throw new ArgumentNullException(nameof(literals));
        if (arr.Length == 0)
            throw new ArgumentException("ExactlyOne requires at least one literal.", nameof(literals));

        AddAtLeastOne(arr);
        AddAtMostOne(arr);
    }

    public void AddExactlyOne(IEnumerable<Variable> variables)
        => AddExactlyOne(variables.Select(v => (Literal)v));

    public string ToDimacs(bool includeComments = true)
    {
        var sb = new StringBuilder();

        if (includeComments)
        {
            sb.AppendLine("c Generated by AGIQ.CNF");
            foreach (var v in _variables)
            {
                sb.Append("c var ")
                  .Append(v.Id)
                  .Append(' ')
                  .AppendLine(SanitizeComment(v.Name));
            }
        }

        sb.Append("p cnf ")
          .Append(VariableCount)
          .Append(' ')
          .Append(ClauseCount)
          .AppendLine();

        foreach (var clause in _clauses)
        {
            foreach (var lit in clause)
            {
                sb.Append(lit.ToDimacs())
                  .Append(' ');
            }

            sb.AppendLine("0");
        }

        return sb.ToString();
    }

    public void Save(string path, bool includeComments = true)
    {
        if (string.IsNullOrWhiteSpace(path))
            throw new ArgumentException("Path is required.", nameof(path));

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, ToDimacs(includeComments), Encoding.UTF8);
    }

    private static string SanitizeComment(string value)
        => value.Replace('\r', ' ').Replace('\n', ' ').Trim();
}

public readonly record struct Variable(int Id, string Name)
{
    public static implicit operator Literal(Variable variable) => new(variable.Id, false);
    public static Literal operator !(Variable variable) => new(variable.Id, true);

    public override string ToString() => Name;
}

public readonly record struct Literal(int VarId, bool IsNegated)
{
    public int ToDimacs() => IsNegated ? -VarId : VarId;

    public Literal Negate() => new(VarId, !IsNegated);

    public static Literal operator !(Literal literal) => literal.Negate();

    public override string ToString()
        => IsNegated ? $"¬x{VarId}" : $"x{VarId}";
}
